#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

OID_OBJECT_RSA_ENCRYPTION="iso.member-body.us.rsadsi.pkcs.pkcs-1.rsaEncryption"
OID_OBJECT_EC_PUBLIC_KEY="iso.member-body.us.ansi-x962.keyType.ecPublicKey"
OID_OBJECT_EC_P256="iso.member-body.us.ansi-x962.curves.prime.prime256v1"
OID_OBJECT_EC_P384="iso.identified-organization.certicom.curve.ansip384r1"
OID_OBJECT_EC_P521="iso.identified-organization.certicom.curve.ansip521r1"

yellow() {
  echo -ne "\033[33m"
  echo -n "$@"
  echo -e "\033[0m"
}

green() {
  echo -ne "\033[32m"
  echo -n "$@"
  echo -e "\033[0m"
}

red() {
  echo -ne "\033[31m"
  echo -n "$@"
  echo -e "\033[0m"
}

fail() {
  echo "$@" >&2
  exit 1
}

base64url_decode() {
  local input
  input="$(cat)"

  input="${input//-/+}"
  input="${input//_//}"

  local mod=$(( ${#input} % 4 ))
  if [ $mod -eq 2 ]; then
    input="${input}=="
  elif [ $mod -eq 3 ]; then
    input="${input}="
  fi

  echo -n "$input" | base64 -d
}

read_jwks() {
  declare jwks="$1"

  if [ -f "$jwks" ]; then
    cat "$jwks"
  elif [ "${jwks:0:8}" == "https://" ]; then
    curl -sSf "$jwks"
  else
    fail "JWKS source not a file or URL: $(yellow "$jwks")"
  fi
}

asn1_der_encode_length() {
  declare length="$1"

  if (( length <= 0x80 )); then
    printf "%02X" "$length"
  else
    local hex_length
    hex_length="$(printf "%x" "$length")"
    # zero pad for even length:
    if (( ${#hex_length} % 2 != 0 )); then
      hex_length="0${hex_length}"
    fi

    local num_bytes
    num_bytes=$(( ${#hex_length} / 2 ))

    printf "%02X" $(( 0x80 | num_bytes ))

    local i=0
    while (( i < ${#hex_length} )); do
      printf "%s" "${hex_length:i:2}"
      i=$(( i + 2 ))
    done
  fi | xxd -r -p
}

asn1_datastructure() {
  declare type="$1"

  echo -n "$type"

  local data
  data="$(cat | base64)"
  local data_length
  # bash can’t handle or even count null values :shrug:
  data_length="$(echo "$data" | base64 -d | LC_CTYPE=C LC_ALL=C sed s/././g)"

  asn1_der_encode_length "${#data_length}"
  echo -n "$data" | base64 -d
}

asn1_sequence() {
  asn1_datastructure $'\x30'
}

asn1_nothing() {
  asn1_datastructure $'\x05' </dev/null
}

asn1_bitstring_positive() {
  { printf "\x00"; cat; } | asn1_datastructure $'\x03'
}

asn1_integer() {
  asn1_datastructure $'\x02'
}

asn1_integer_positive() {
  { printf "\x00"; cat; } | asn1_integer
}

asn1_encode_int() {
	declare n="$1"
	local i bytes=()

	# take 7 bit chunks until there is nothing left
	while :; do
		bytes+=($((n & 0x7F)))
		n=$((n >> 7))

		if (( n == 0 )); then
		  break
    fi
	done

	# output from the end. add continuation bit to all but last
	for ((i=${#bytes[@]}-1; i>=0; i--)); do
		local b="${bytes[i]}"
		if (( i != 0 )); then
			b=$((b | 0x80))
		fi
		printf '%02x' "$b"
	done
}

asn1_encode_oid() {
	local oid="$1"
	IFS='.' read -ra parts <<< "$oid"

	local first=$((40 * parts[0] + parts[1]))
	printf '%02x' "$first"

	for ((i=2; i<${#parts[@]}; i++)); do
		asn1_encode_int "${parts[i]}"
	done
}

asn1_object_identifier() {
  declare oid="$1"

  case "$oid" in
    "$OID_OBJECT_RSA_ENCRYPTION")
      # https://oid-base.com/get/1.2.840.113549.1.1.1
      asn1_encode_oid "1.2.840.113549.1.1.1"
      ;;
    "$OID_OBJECT_EC_PUBLIC_KEY")
      # https://oid-base.com/get/1.2.840.10045.2.1
      asn1_encode_oid "1.2.840.10045.2.1"
      ;;
    "$OID_OBJECT_EC_P256")
      # https://std.neuromancer.sk/nist/P-256
      # https://oid-base.com/get/1.2.840.10045.3.1.7
      asn1_encode_oid "1.2.840.10045.3.1.7"
      ;;
    "$OID_OBJECT_EC_P384")
      # https://std.neuromancer.sk/nist/P-384
      # https://oid-base.com/get/1.3.132.0.34
      asn1_encode_oid "1.3.132.0.34"
      ;;
    "$OID_OBJECT_EC_P521")
      # https://std.neuromancer.sk/nist/P-521
      # https://oid-base.com/get/1.3.132.0.35
      asn1_encode_oid "1.3.132.0.35"
      ;;
    *)
      fail "unsupported object identifier $(yellow "$oid")"
  esac | xxd -r -p | asn1_datastructure $'\x06'
}

pem_wrapper() {
  asn1_sequence | base64 -w 64
}

generate_rsa() {
  declare key="$1"

  local mod exp
  mod="$(jq -r .n <<<"$key")"
  exp="$(jq -r .e <<<"$key")"

  {
    asn1_object_identifier "$OID_OBJECT_RSA_ENCRYPTION"
    asn1_nothing
  } | asn1_sequence

  {
    echo "$mod" | base64url_decode | asn1_integer_positive
    echo "$exp" | base64url_decode | asn1_integer
  } | asn1_sequence | asn1_bitstring_positive
}

generate_ec() {
  declare key="$1"

  local crv x y
  crv="$(jq -r .crv <<<"$key")"
  x="$(jq -r .x <<<"$key")"
  y="$(jq -r .y <<<"$key")"

  local curve_oid
  curve_oid="$(
    case "$crv" in
      "P-256")
        echo "$OID_OBJECT_EC_P256"
        ;;
      "P-384")
        echo "$OID_OBJECT_EC_P384"
        ;;
      "P-521")
        echo "$OID_OBJECT_EC_P521"
        ;;
      *)
        fail "Unsupported curve type $(yellow "$crv")"
    esac
  )"

  {
    asn1_object_identifier "$OID_OBJECT_EC_PUBLIC_KEY"
    asn1_object_identifier "$curve_oid"
  } | asn1_sequence

  {
    printf "\x04" # compressed form
    echo "$x" | base64url_decode
    echo "$y" | base64url_decode
  } | asn1_bitstring_positive
}

write_single_key() {
  declare output_dir="$1" key="$2"

  local kty kid payload
  kid="$(jq -r .kid <<<"$key")"
  kty="$(jq -r .kty <<<"$key")"

  if [ -z "$kid" ]; then
    fail "Key does not have an ID, cannot save"
  fi

  case "$kty" in
    "RSA")
      payload="$(generate_rsa "$key" | pem_wrapper)"
      ;;
    "EC")
      payload="$(generate_ec "$key" | pem_wrapper)"
      ;;
    *)
      fail "Unsupported key type $(yellow "$kty") for key $(yellow "$kid")"
      ;;
  esac

  local output_path="$output_dir/$kid.pem"
  echo "Writing to $(yellow "$output_path")"
  {
    echo '-----BEGIN PUBLIC KEY-----'
    echo "$payload"
    echo '-----END PUBLIC KEY-----'
  } > "$output_path"
}

write_keys() {
  declare output_dir="$1"
  local json_line

  while read -r json_line; do
    write_single_key "$output_dir" "$json_line"
  done
}

main() {
  declare jwks="${1:-/dev/stdin}" output_dir="${2:-.}"

  if [ ! -d "$output_dir" ]; then
    echo "Creating output directory $(yellow "$output_dir")"
    mkdir -p "$output_dir"
  fi

  read_jwks "$jwks" |
    jq -cM '.keys|.[]' |
    write_keys "$output_dir"
}

main "$@"
